Site/Controllers/AreaRiservataController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Site.Helpers;
using Site.Helpers.Extensions;
using Site.Models;
using Site.Models.Dtos;
using Site.Models.Entities;
using Site.Models.Views;
using System.Data;

namespace Site.Controllers
{
    [Authorize]
    public class AreaRiservataController : Controller
    {
        public IActionResult Index()
        {
            var utenteLoggato = HttpContext.Session.GetObject<Utente>("UtenteLoggato");
            if (utenteLoggato == null)
                return RedirectToAction("Login", "Account");
            ViewData["UtenteLoggato"] = utenteLoggato;
            var model = new AreaRiservataViewModel();
            model.Id = utenteLoggato.Id;
            model.FileFoto = utenteLoggato.Foto;
            model.Utente = utenteLoggato;
            return View(model);
        }

        [HttpPost]
        public IActionResult ModificaFoto(UtenteDto utenteDto)
        {
            var utenteLoggato = HttpContext.Session.GetObject<Utente>("UtenteLoggato");
            if (utenteLoggato == null)
                return RedirectToAction("Login", "Account");
            ViewData["UtenteLoggato"] = utenteLoggato;
            //se arriva un'immagine salvarla su filesystem (wwwroot/uploads/utente/{id}/<file>)
            //e modificare il db impostando il campo foto a <file>

            if (utenteDto.FileFoto != null)
            {
                //1) aggiorno database
                utenteLoggato.Foto = utenteDto.FileFoto.FileName;
                DatabaseHelper.SalvaUtente(utenteLoggato);
                HttpContext.Session.SetObject("UtenteLoggato", utenteLoggato);

                //2) creo il file su filesystem
                var path = PathHelper.GetPathUtente(utenteDto.Id); //recupero il percorso dell'utente
                if (!Directory.Exists(path))
                {
                    //1)creazione cartella nazioni/id in uploads se non esiste con id quello del modello
                    Directory.CreateDirectory(path);
                }
                //salvare il contenuto di FileFoto nel percorso creato
                var filePath = path + "\\" + utenteLoggato.Foto;
                using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                {
                    try
                    {
                        utenteDto.FileFoto.CopyTo(fileStream);
                    }
                    catch (Exception ex)
                    {

                    }
                }
            }
            var model = new AreaRiservataViewModel();
            model.Id = utenteLoggato.Id;
            model.FileFoto = utenteLoggato.Foto;
            model.Utente = utenteLoggato;
            return View("Index", model);
        }

        [HttpGet]
        public IActionResult ScaricaExcelPersonale()
        {
            var lista = DatabaseHelper.GetAllPersonale();

            byte[] fileBytes = ExcelHelper.CreaFileExcelListaPersonale(lista);

            //byte[] fileBytes = System.IO.File.ReadAllBytes(@"e:\personale.xlsx");
            string fileName = "personale.xlsx";
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);

            //return View(); //deve essere un file non una view
        }



        [HttpGet]
        public IActionResult CreaPersonale()
        {
            var model = new CreaPersonaleViewModel
            {
                Pagina = Costanti.Pagine.Personale,
                ListaPersonale = DatabaseHelper.GetAllPersonale()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult CreaPersonale(PersonaleDto dto)
        {
            var model = new CreaPersonaleViewModel
            {
                Pagina = Costanti.Pagine.Personale,
                ListaPersonale = DatabaseHelper.GetAllPersonale(),
                Cognome = dto.Cognome
            };
            if (ModelState.IsValid)
            {
                if (dto.SuperioreId == 0)
                    dto.SuperioreId = null;
                //insert su database
                var utente = DatabaseHelper.SalvaPersonale(dto);

                //dopo aver creato la modifica, manderemo la.
                ViewData["MsgOk"] = "Record aggiunto con successo";
                return View(model);
            }

            ViewData["MsgKo"] = "Errore, riprova più tardi";
            return View(model);
        }


        [HttpGet]
        public IActionResult ModificaPersonale(int id)
        {
            var personale = DatabaseHelper.GetPersonaleById(id);
            var model = new ModificaPersonaleViewModel(personale)
            {
                Pagina = Costanti.Pagine.Personale,
                ListaPersonale = DatabaseHelper.GetAllPersonale()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult ModificaPersonale(PersonaleDto dto)
        {
            var model = new ModificaPersonaleViewModel(dto)
            {
                Pagina = Costanti.Pagine.Personale,
                ListaPersonale = DatabaseHelper.GetAllPersonale(),
            };
            if (ModelState.IsValid && dto.Id != null && dto.Id.Value > 0)
            {
                //insert su database
                var utente = DatabaseHelper.SalvaPersonale(dto);

                //dopo aver creato la modifica, manderemo la.
                ViewData["MsgOk"] = "Record aggiornato con successo";
                return View(model);
            }

            ViewData["MsgKo"] = "Errore, riprova più tardi";
            return View(model);
        }

        [HttpGet]
        public IActionResult CancellaPersonale(int id)
        {
            DatabaseHelper.DeletePersonaleById(id);

            return RedirectToAction("Personale", "Home");
        }

    }
}

Site/Views/Shared/_Layout.cshtml
@using Site.Models.Entities;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ospedale</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ospedale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item @(Model!=null && Model.Pagina==Costanti.Pagine.Home?"active":string.Empty)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item @(Model!=null && Model.Pagina==Costanti.Pagine.Personale?"active":string.Empty)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Personale">Personale</a>
                        </li>
                        <li class="nav-item @(Model!=null && Model.Pagina==Costanti.Pagine.Pazienti?"active":string.Empty)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Pazienti">Pazienti</a>
                        </li>
                        <li class="nav-item @(Model!=null && Model.Pagina==Costanti.Pagine.Visite?"active":string.Empty)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Visite">Visite</a>
                        </li>
                        <li class="nav-item @(Model!=null && Model.Pagina==Costanti.Pagine.Privacy?"active":string.Empty)">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                    <div class="form-inline my-2 my-lg-0">
                        @if (!string.IsNullOrWhiteSpace(Html.ViewContext.HttpContext.User.Identity.Name))
                        {
                            <a class="nav-link text-dark" asp-area="" asp-controller="AreaRiservata" asp-action="Index"><span>@Html.ViewContext.HttpContext.User.Identity.Name</span></a>
                            <a class="btn btn-outline-dark my-2 my-sm-0 @(Model!=null && Model.Pagina==Costanti.Pagine.Login?"active":string.Empty)" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>

                        }
                        else
                        {
                            <a class="btn btn-outline-dark my-2 my-sm-0 @(Model!=null && Model.Pagina==Costanti.Pagine.Registrazione?"active":string.Empty)" asp-area="" asp-controller="Account" asp-action="Registrazione">Registrazione</a>
                            <a class="btn btn-outline-dark my-2 my-sm-0 @(Model!=null && Model.Pagina==Costanti.Pagine.Login?"active":string.Empty)" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted fixed-bottom">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>